import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import type { Event } from "@/types";
import type { PrepBreakdownData } from "@/lib/actions/production";

// ── Shared palette (matches generateProductionPDFs) ──

const HEADER_BG: [number, number, number] = [26, 37, 56];
const TEXT_WHITE: [number, number, number] = [255, 255, 255];
const TEXT_DARK: [number, number, number] = [30, 30, 30];
const MUTED: [number, number, number] = [120, 120, 120];
const ALT_ROW: [number, number, number] = [245, 247, 250];
const BORDER: [number, number, number] = [210, 215, 220];
const ACCENT: [number, number, number] = [212, 163, 115]; // #D4A373

const MARGIN = 48;

function createDoc(): { doc: jsPDF; pageW: number; pageH: number } {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  return { doc, pageW, pageH };
}

function tableStyles() {
  return {
    styles: {
      fontSize: 9,
      cellPadding: 6,
      textColor: TEXT_DARK,
      lineColor: BORDER,
      lineWidth: 0.25,
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: TEXT_WHITE,
      fontStyle: "bold" as const,
      fontSize: 8.5,
    },
    alternateRowStyles: {
      fillColor: ALT_ROW,
    },
  };
}

function drawHeader(
  doc: jsPDF,
  pageW: number,
  title: string,
  subtitle: string,
  companyName?: string
): number {
  doc.setFillColor(...HEADER_BG);
  doc.rect(0, 0, pageW, companyName ? 80 : 70, "F");

  let yTop = 28;

  if (companyName) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(180, 190, 200);
    doc.text(companyName.toUpperCase(), MARGIN, yTop);
    yTop += 22;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...TEXT_WHITE);
  doc.text(title, MARGIN, yTop);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(180, 190, 200);
  doc.text(subtitle, MARGIN, yTop + 16);
  doc.text(`Generated ${format(new Date(), "MMMM d, yyyy")}`, pageW - MARGIN, yTop, {
    align: "right",
  });

  return companyName ? 100 : 90;
}

function drawEventInfo(doc: jsPDF, event: Event, guestCount: number, y: number): number {
  const dateStr = format(new Date(event.event_date), "EEEE, MMMM d, yyyy");
  const info = [
    ["Client", event.client_name],
    ["Date", dateStr],
    ["Guests", String(guestCount)],
    ["Venue", event.venue ?? "TBD"],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    body: info,
    showHead: false,
    ...tableStyles(),
    styles: {
      ...tableStyles().styles,
      cellPadding: 5,
      fontSize: 8.5,
    },
    columnStyles: {
      0: { cellWidth: 70, fontStyle: "bold", textColor: MUTED },
    },
  });

  return doc.lastAutoTable.finalY + 16;
}

function addFooters(doc: jsPDF, pageW: number, pageH: number, label: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(`${label} · Generated by Cateros`, MARGIN, pageH - 24);
    doc.text(`Page ${i} of ${pageCount}`, pageW - MARGIN, pageH - 24, { align: "right" });
  }
}

function stationLabel(station: string): string {
  return station.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// ─────────────────────────────────────────────────────────────────────
// Main Export: Kitchen Prep Breakdown PDF
// ─────────────────────────────────────────────────────────────────────

export function generatePrepBreakdownPDF(
  event: Event,
  data: PrepBreakdownData,
  companyName?: string
): jsPDF {
  const { doc, pageW, pageH } = createDoc();

  let y = drawHeader(doc, pageW, "KITCHEN PREP BREAKDOWN", event.name, companyName);
  y = drawEventInfo(doc, event, data.guestCount, y);

  // ── Section 1: Production Tasks by Station ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...HEADER_BG);
  doc.text("PRODUCTION TASKS BY STATION", MARGIN, y);
  y += 6;

  // Group tasks by station
  const stationMap = new Map<string, typeof data.kitchenTasks>();
  for (const task of data.kitchenTasks) {
    const key = task.station;
    if (!stationMap.has(key)) stationMap.set(key, []);
    stationMap.get(key)!.push(task);
  }

  for (const [station, tasks] of stationMap) {
    if (y > 640) {
      doc.addPage();
      y = MARGIN;
    }

    // Station header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...ACCENT);
    doc.text(stationLabel(station).toUpperCase(), MARGIN, y);
    y += 4;

    const rows = tasks.map((t) => {
      const ingList = t.ingredients.length > 0
        ? t.ingredients.map((i) => `${i.name}: ${i.quantity} ${i.unit}`).join("\n")
        : "—";
      return [
        "[ ]",
        t.taskName,
        t.dishName,
        `${t.batchQuantity} ${t.unit}`,
        ingList,
        t.prepNotes ?? "",
      ];
    });

    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Done", "Task", "For Dish", "Batch Qty", "Ingredients", "Notes"]],
      body: rows,
      ...tableStyles(),
      columnStyles: {
        0: { cellWidth: 30, halign: "center" },
        1: { cellWidth: 90, fontStyle: "bold" },
        2: { cellWidth: 80 },
        3: { cellWidth: 55, halign: "right" },
        4: { cellWidth: 140, fontSize: 7.5 },
        5: { cellWidth: 90, fontSize: 7.5 },
      },
    });

    y = doc.lastAutoTable.finalY + 16;
  }

  // ── Section 2: Master Ingredient List ──
  if (y > 580) {
    doc.addPage();
    y = MARGIN;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...HEADER_BG);
  doc.text("MASTER INGREDIENT LIST", MARGIN, y);
  y += 6;

  const ingredientRows = data.byIngredient.map((ing) => [
    ing.ingredientName,
    String(ing.totalQuantity),
    ing.unit,
    ing.dishes.map((d) => d.dishName).join(", "),
    ing.inventoryStatus === "in_stock"
      ? `In Stock (${ing.inventoryAvailable})`
      : ing.inventoryStatus === "low"
        ? `Low (${ing.inventoryAvailable})`
        : ing.inventoryStatus === "not_in_stock"
          ? "Not in Stock"
          : "—",
    ing.needsOrdering ? "YES" : "",
  ]);

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Ingredient", "Total Qty", "Unit", "Used In", "Inventory", "Order?"]],
    body: ingredientRows,
    ...tableStyles(),
    columnStyles: {
      0: { fontStyle: "bold" },
      1: { cellWidth: 55, halign: "right" },
      2: { cellWidth: 40, halign: "center" },
      3: { cellWidth: 130, fontSize: 7.5 },
      4: { cellWidth: 70, fontSize: 7.5 },
      5: { cellWidth: 40, halign: "center", fontStyle: "bold" },
    },
    didParseCell(hookData: any) {
      // Highlight "Order?" column
      if (hookData.section === "body" && hookData.column.index === 5 && hookData.cell.raw === "YES") {
        hookData.cell.styles.textColor = [180, 50, 50];
        hookData.cell.styles.fontStyle = "bold";
      }
      // Color inventory status
      if (hookData.section === "body" && hookData.column.index === 4) {
        const val = hookData.cell.raw as string;
        if (val.startsWith("In Stock")) hookData.cell.styles.textColor = [34, 120, 60];
        else if (val.startsWith("Low")) hookData.cell.styles.textColor = [180, 120, 30];
        else if (val === "Not in Stock") hookData.cell.styles.textColor = [180, 50, 50];
      }
    },
  });

  y = doc.lastAutoTable.finalY + 16;

  // ── Section 3: Dish Breakdown ──
  if (y > 580) {
    doc.addPage();
    y = MARGIN;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...HEADER_BG);
  doc.text("DISH BREAKDOWN", MARGIN, y);
  y += 6;

  for (const dish of data.byDish) {
    if (y > 640) {
      doc.addPage();
      y = MARGIN;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...HEADER_BG);
    doc.text(`${dish.dishName}  —  ${dish.quantityNeeded} servings (${dish.scaleFactor.toFixed(1)}x)`, MARGIN, y);
    y += 4;

    if (dish.ingredients.length > 0) {
      const dishIngRows = dish.ingredients.map((ing) => [ing.name, String(ing.quantity), ing.unit]);

      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        head: [["Ingredient", "Quantity", "Unit"]],
        body: dishIngRows,
        ...tableStyles(),
        columnStyles: {
          1: { cellWidth: 60, halign: "right" },
          2: { cellWidth: 60, halign: "center" },
        },
      });

      y = doc.lastAutoTable.finalY + 6;
    } else {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text("No recipe linked", MARGIN + 8, y + 4);
      y += 14;
    }

    if (dish.prepNotes) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      const lines = doc.splitTextToSize(dish.prepNotes, pageW - MARGIN * 2);
      doc.text(lines, MARGIN + 8, y);
      y += lines.length * 9 + 6;
    }

    y += 10;
  }

  addFooters(doc, pageW, pageH, "Kitchen Prep Breakdown");
  return doc;
}
