import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { safeParseDate } from "@/lib/utils";
import type { Event, EventPrepItem, EventShoppingItem, EventPackItem } from "@/types";

// ── Shared palette & config ──

const HEADER_BG: [number, number, number] = [26, 37, 56];
const TEXT_WHITE: [number, number, number] = [255, 255, 255];
const TEXT_DARK: [number, number, number] = [30, 30, 30];
const MUTED: [number, number, number] = [120, 120, 120];
const ALT_ROW: [number, number, number] = [245, 247, 250];
const BORDER: [number, number, number] = [210, 215, 220];

const MARGIN = 48;

function createDoc(): { doc: jsPDF; pageW: number; pageH: number } {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  return { doc, pageW, pageH };
}

function tableStyles() {
  return {
    styles: {
      fontSize: 9,
      cellPadding: 6,
      textColor: TEXT_DARK,
      lineColor: BORDER,
      lineWidth: 0.25,
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: TEXT_WHITE,
      fontStyle: "bold" as const,
      fontSize: 8.5,
    },
    alternateRowStyles: {
      fillColor: ALT_ROW,
    },
  };
}

function drawHeader(
  doc: jsPDF,
  pageW: number,
  title: string,
  eventName: string,
  companyName?: string
): number {
  // Header band
  doc.setFillColor(...HEADER_BG);
  doc.rect(0, 0, pageW, companyName ? 80 : 70, "F");

  let yTop = 28;

  if (companyName) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(180, 190, 200);
    doc.text(companyName.toUpperCase(), MARGIN, yTop);
    yTop += 22;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...TEXT_WHITE);
  doc.text(title, MARGIN, yTop);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(180, 190, 200);
  doc.text(eventName, MARGIN, yTop + 16);
  doc.text(`Generated ${format(new Date(), "MMMM d, yyyy")}`, pageW - MARGIN, yTop, {
    align: "right",
  });

  return companyName ? 100 : 90;
}

function drawEventInfo(doc: jsPDF, event: Event, y: number): number {
  const dateStr = format(safeParseDate(event.event_date), "EEEE, MMMM d, yyyy");
  const info = [
    ["Client", event.client_name],
    ["Date", dateStr],
    ["Guests", String(event.guest_count)],
    ["Venue", event.venue ?? "TBD"],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    body: info,
    showHead: false,
    ...tableStyles(),
    styles: {
      ...tableStyles().styles,
      cellPadding: 5,
      fontSize: 8.5,
    },
    columnStyles: {
      0: { cellWidth: 70, fontStyle: "bold", textColor: MUTED },
    },
  });

  return doc.lastAutoTable.finalY + 16;
}

function addFooters(
  doc: jsPDF,
  pageW: number,
  pageH: number,
  label: string,
  companyName?: string
) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);

    const left = companyName
      ? `${companyName} · ${label} · Generated by Cateros`
      : `${label} · Generated by Cateros`;
    doc.text(left, MARGIN, pageH - 24);
    doc.text(`Page ${i} of ${pageCount}`, pageW - MARGIN, pageH - 24, { align: "right" });
  }
}

function formatTime(time: string | null): string {
  if (!time) return "";
  const [h, m] = time.split(":");
  const hour = parseInt(h);
  const ampm = hour >= 12 ? "PM" : "AM";
  const display = hour > 12 ? hour - 12 : hour === 0 ? 12 : hour;
  return `${display}:${m} ${ampm}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. Prep Sheet — breakdown by menu item
// ─────────────────────────────────────────────────────────────────────────────

export function generatePrepSheetPDF(
  event: Event,
  prepItems: EventPrepItem[],
  companyName?: string
): jsPDF {
  const { doc, pageW, pageH } = createDoc();

  let y = drawHeader(doc, pageW, `PREP SHEET — ${event.name}`, event.name, companyName);
  y = drawEventInfo(doc, event, y);

  // Group prep items by menu_item_name
  const groups = new Map<string, EventPrepItem[]>();
  for (const item of prepItems) {
    const key = item.menu_item_name;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(item);
  }

  for (const [menuItemName, items] of groups) {
    // Check if we need a new page
    if (y > 660) {
      doc.addPage();
      y = MARGIN;
    }

    // Section title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...HEADER_BG);
    doc.text(menuItemName, MARGIN, y);
    y += 8;

    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Component", "Quantity", "Unit", "Station", "Notes"]],
      body: items.map((item) => [
        item.component_name,
        String(item.required_quantity),
        item.unit,
        item.station ?? "—",
        item.prep_notes ?? "",
      ]),
      ...tableStyles(),
      columnStyles: {
        1: { cellWidth: 60, halign: "right" },
        2: { cellWidth: 50, halign: "center" },
        3: { cellWidth: 80 },
        4: { cellWidth: 120 },
      },
    });

    y = doc.lastAutoTable.finalY + 20;
  }

  addFooters(doc, pageW, pageH, "Prep Sheet", companyName);
  return doc;
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Consolidated Prep — merged totals
// ─────────────────────────────────────────────────────────────────────────────

export function generateConsolidatedPrepPDF(
  event: Event,
  prepItems: EventPrepItem[],
  companyName?: string
): jsPDF {
  const { doc, pageW, pageH } = createDoc();

  let y = drawHeader(
    doc,
    pageW,
    `CONSOLIDATED PREP — ${event.name}`,
    event.name,
    companyName
  );
  y = drawEventInfo(doc, event, y);

  // Merge quantities by component + unit + station
  const merged = new Map<string, { component: string; totalQty: number; unit: string; station: string }>();
  for (const item of prepItems) {
    const key = `${item.component_name}||${item.unit}||${item.station ?? ""}`;
    const existing = merged.get(key);
    if (existing) {
      existing.totalQty += item.required_quantity;
    } else {
      merged.set(key, {
        component: item.component_name,
        totalQty: item.required_quantity,
        unit: item.unit,
        station: item.station ?? "—",
      });
    }
  }

  // Sort by station then alphabetically by component
  const sorted = Array.from(merged.values()).sort((a, b) => {
    const stationCmp = a.station.localeCompare(b.station);
    if (stationCmp !== 0) return stationCmp;
    return a.component.localeCompare(b.component);
  });

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Component", "Total Qty", "Unit", "Station"]],
    body: sorted.map((row) => [
      row.component,
      String(Math.ceil(row.totalQty * 100) / 100),
      row.unit,
      row.station,
    ]),
    ...tableStyles(),
    columnStyles: {
      1: { cellWidth: 70, halign: "right" },
      2: { cellWidth: 60, halign: "center" },
      3: { cellWidth: 90 },
    },
  });

  addFooters(doc, pageW, pageH, "Consolidated Prep", companyName);
  return doc;
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. Station Prep — single station
// ─────────────────────────────────────────────────────────────────────────────

export function generateStationPrepPDF(
  event: Event,
  prepItems: EventPrepItem[],
  station: string,
  companyName?: string
): jsPDF {
  const { doc, pageW, pageH } = createDoc();

  const stationLabel = station
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  let y = drawHeader(
    doc,
    pageW,
    `STATION PREP: ${stationLabel} — ${event.name}`,
    event.name,
    companyName
  );
  y = drawEventInfo(doc, event, y);

  // Filter to the given station
  const filtered = prepItems.filter(
    (item) => item.station === station
  );

  if (filtered.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text("No prep items assigned to this station.", MARGIN, y + 10);
  } else {
    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Component", "Qty", "Unit", "Menu Item", "Notes"]],
      body: filtered.map((item) => [
        item.component_name,
        String(item.required_quantity),
        item.unit,
        item.menu_item_name,
        item.prep_notes ?? "",
      ]),
      ...tableStyles(),
      columnStyles: {
        1: { cellWidth: 50, halign: "right" },
        2: { cellWidth: 50, halign: "center" },
        3: { cellWidth: 120 },
        4: { cellWidth: 120 },
      },
    });
  }

  addFooters(doc, pageW, pageH, `Station Prep: ${stationLabel}`, companyName);
  return doc;
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Shopping List
// ─────────────────────────────────────────────────────────────────────────────

export function generateShoppingListPDF(
  event: Event,
  shoppingItems: EventShoppingItem[],
  companyName?: string
): jsPDF {
  const { doc, pageW, pageH } = createDoc();

  let y = drawHeader(
    doc,
    pageW,
    `SHOPPING LIST — ${event.name}`,
    event.name,
    companyName
  );
  y = drawEventInfo(doc, event, y);

  // Sort alphabetically
  const sorted = [...shoppingItems].sort((a, b) =>
    a.ingredient_name.localeCompare(b.ingredient_name)
  );

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["✓", "Ingredient", "Quantity", "Unit", "Vendor"]],
    body: sorted.map((item) => [
      item.purchased ? "☑" : "☐",
      item.ingredient_name,
      String(Math.ceil(item.quantity * 100) / 100),
      item.unit,
      item.vendor ?? "—",
    ]),
    ...tableStyles(),
    columnStyles: {
      0: { cellWidth: 28, halign: "center", fontSize: 11 },
      2: { cellWidth: 60, halign: "right" },
      3: { cellWidth: 55, halign: "center" },
      4: { cellWidth: 90 },
    },
  });

  addFooters(doc, pageW, pageH, "Shopping List", companyName);
  return doc;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. Pack List
// ─────────────────────────────────────────────────────────────────────────────

export function generatePackListPDF(
  event: Event,
  packItems: EventPackItem[],
  companyName?: string
): jsPDF {
  const { doc, pageW, pageH } = createDoc();

  let y = drawHeader(
    doc,
    pageW,
    `PACK LIST — ${event.name}`,
    event.name,
    companyName
  );
  y = drawEventInfo(doc, event, y);

  // Group by category
  const groups = new Map<string, EventPackItem[]>();
  for (const item of packItems) {
    const cat = item.category || "Uncategorized";
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat)!.push(item);
  }

  for (const [category, items] of groups) {
    if (y > 660) {
      doc.addPage();
      y = MARGIN;
    }

    // Category heading
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...HEADER_BG);
    doc.text(category, MARGIN, y);
    y += 8;

    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Item", "Quantity", "✓", "Notes"]],
      body: items.map((item) => [
        item.item_name,
        String(item.quantity),
        item.packed ? "☑" : "☐",
        item.notes ?? "",
      ]),
      ...tableStyles(),
      columnStyles: {
        1: { cellWidth: 60, halign: "right" },
        2: { cellWidth: 28, halign: "center", fontSize: 11 },
        3: { cellWidth: 140 },
      },
    });

    y = doc.lastAutoTable.finalY + 20;
  }

  addFooters(doc, pageW, pageH, "Pack List", companyName);
  return doc;
}
